### ISSUE TITLE
`RuntimeException` when generating client with nested field 

### ISSUE THREAD

**Issue by JeppeKlitgaard** [mathworks-ref-arch/matlab-openapi-generator#1]
I am trying to use the generator to create a REST client in MATLAB. The OpenAPI schema is generated by `utoipa` on a Rust/Axum server. Other OpenAPI generators (Dart, Python) are able to correctly produce clients without error.

The MATLAB generator raises a `RuntimeException` when generating a model for a simple object containing a number of `double`s:
```
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'LoopCNT'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:583)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:960)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:511)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: org.openapitools.codegen.templating.TemplateNotFoundException: model.mustache
        at org.openapitools.codegen.TemplateManager.getFullTemplateFile(TemplateManager.java:54)
        at org.openapitools.codegen.TemplateManager.getFullTemplateContents(TemplateManager.java:72)
        at org.openapitools.codegen.templating.MustacheEngineAdapter.compileTemplate(MustacheEngineAdapter.java:63)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:163)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1106)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1093)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:423)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:574)
        ... 4 more
```

The `LoopCNT` object containings 9 fields that are all `double` in the OpenAPI Spec. `LoopCNT` is itself used as a field on another object.

I am happy to provide a full debug trace and the OpenAPI Schema in a non-public manner. I can be reached at `jkl@nanonord.dk`

**Comment by brownemi** [comment]
Hi, thanks for reporting this. An object with just doubles should work fine and the model.mustache file mentioned in the message is present in the repo, so that template not found message is likely misleading. We'll probably need to see the spec in this case. I'll contact you via email as suggested.

**Comment by JeppeKlitgaard** [comment]
I liased over e-mail and we figured out the solution is to add:
```
    -t vendored/matlab-openapi-generator/Software/Mustache \
    --additional-properties openapiRoot="vendored/matlab-openapi-generator/Software/MATLAB" \
```

To the `openapi-generator-cli` command when generating the project.

**Comment by brownemi** [comment]
Documentation updates in the next release (1.0.7) will clarify this.
Closing the issue, thanks!
